version: '3'
services:
  django:
    build: ./django
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: thisisnotsecure
    restart: always
