version: '3'
services:
  django:
    build: ./django
    ports:
      - 8000:8000
    environment:
     - BG_COLOR
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=thisisnotsecure
    restart: always
